kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: rbac
subjects:
  - kind: ServiceAccount
    name: example-sa
    namespace: rbac
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io
